# Use an official Node.js runtime as a base image
FROM node:14

# Set the working directory inside the container
WORKDIR /app

# Create an SSH directory
RUN mkdir -p /root/.ssh



#RUN echo "test"

# Copy your SSH private key into the container
COPY id_rsa /root/.ssh/id_rsa

# Set correct permissions for the SSH key
#RUN chmod 600 /root/.ssh/id_rsa

# Add GitHub's SSH host key to known_hosts
#RUN ssh-keyscan github.com >> /root/.ssh/known_hosts

# Copy package.json and package-lock.json (if available)
#COPY package*.json ./

# Install application dependencies
#RUN npm install

# Copy your application source code into the container
#COPY . .

# Specify the command to run when the container starts
#CMD [ "node", "app.js" ]

